### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by nycdotnet** [ryanmurakami/pluralsight-hapi-starter-code#2]
Hi Ryan,

I think you may have forgotten to include Bootstrap in this.  The presentation doesn't look right without adding that.

-Steve O

**Comment by ryanmurakami** [comment]
Hi Steve!

Thanks for the comment. I used Bootstrap when developing the course, but replaced it with custom styles which are in the public/css/stylesheet.css file. 

What is your project looking like?

**Comment by nycdotnet** [comment]
Perhaps there was a merge problem of some sort.  This is what I see after downloading a ZIP of the content of this repo and copying it into the folder (as a customer might do):

![hapi-no-bootstrap](https://cloud.githubusercontent.com/assets/3755379/8456675/06e895f8-1fdb-11e5-9f70-3de3120b7cd2.png)

When I also copy the default Bootstrap and Boostrap theme CSS file and link in the stylesheet.css file, it looks the same as in your video.

```
@import "bootstrap.css";
@import "bootstrap-theme.css";
```

**Comment by ryanmurakami** [comment]
Ah, yeah, that does look unstyled. I think the issue is the include statement in the templates/index.html file. The path to the stylesheet is setup for module 2 when we enable a static asset endpoint in our web server. If you change "assets" to "public" on line 4 of templates/index.html, it should enable you to see the styled version when viewing from your file directory. 

I can see how this might be confusing when first looking at the files. I'll add a note to the readme about it.

Thanks!

**Comment by ryanmurakami** [comment]
@nycdotnet Thanks for taking the time to take those screenshots!

**Comment by ryanmurakami** [comment]
Actually, I spoke to soon! You're totally right, Steve, I left out some styles.... Pushing new code now. Thanks for the catch!

**Comment by nycdotnet** [comment]
No worries - will you take a PR to include HTML 5 doctypes and fix the unescaped ampersand on index.html?  IE 11 barfs on that and renders in quirks mode.

**Comment by ryanmurakami** [comment]
I would love one! :-)
